// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx5Q01c1gRY86hyHJRq1Au4P9NEgiOuZg',
    appId: '1:293856820566:web:1d03b9efb872172ecdeaf7',
    messagingSenderId: '293856820566',
    projectId: 'fir-flutter-codelab-adda9',
    authDomain: 'fir-flutter-codelab-adda9.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-adda9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAEM0X1RpdZ0mmSxrZtyF_8fujdDUZsU4',
    appId: '1:293856820566:android:a58fa491d301ee41cdeaf7',
    messagingSenderId: '293856820566',
    projectId: 'fir-flutter-codelab-adda9',
    storageBucket: 'fir-flutter-codelab-adda9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNT643LVxuXmJniLsbBF2XbnmwCy_7BcU',
    appId: '1:293856820566:ios:e7a2a4093a2c3ef8cdeaf7',
    messagingSenderId: '293856820566',
    projectId: 'fir-flutter-codelab-adda9',
    storageBucket: 'fir-flutter-codelab-adda9.appspot.com',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNT643LVxuXmJniLsbBF2XbnmwCy_7BcU',
    appId: '1:293856820566:ios:e7a2a4093a2c3ef8cdeaf7',
    messagingSenderId: '293856820566',
    projectId: 'fir-flutter-codelab-adda9',
    storageBucket: 'fir-flutter-codelab-adda9.appspot.com',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBx5Q01c1gRY86hyHJRq1Au4P9NEgiOuZg',
    appId: '1:293856820566:web:6689943fd58bead3cdeaf7',
    messagingSenderId: '293856820566',
    projectId: 'fir-flutter-codelab-adda9',
    authDomain: 'fir-flutter-codelab-adda9.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-adda9.appspot.com',
  );

}